# Basic settings
basics:
  site_title: Draper Startup House Chiang Mai
  site_base_url: 'https://connectinchiangmai.com'
  site_logo_image: ''
  site_thumb_image: ''
  contact_email: 'example@me.com'
  phone_number: "+555 555 5555"
  address: Chiang Mai, Thailand
social:
  facebook_url: 'https://www.facebook.com/dshchiangmai'
  instagram_url: 'https://instagram.com/dshchiangmai'
  instagram_handle: '@dshchiangmai'
  twitter_url: 'https://twitter.com/dshchiangmai'
  twitter_handle: '@dshchiangmai'
  youtube_url: 'https://youtube.com'
  github_url: 'https://github.com'
  linkedin_url: 'https://www.linkedin.com/company/draperstartuphouse/'
  snapchat_url: 'https://snapchat.com'
  stackoverflow_url: 'https://stackoverflow.com'
navigation:
  menu_1_url: /about
  menu_2_url: /portfolio
  menu_3_url: /blog
  menu_4_url: /contact
  menu_5_url:
  menu_6_url:
# Brand identity
logos:
  navbar_logo_image: ''
  footer_logo_image: ''

# Global colors. Put HEX values between quotes otherwise it will act as a comment in YAML
colors:
  primary_color: "#f2f2f2"
  secondary_color: "#555"
  highlight-color: "#ffcc09"
  secondary_shade_color: "#565"
  accent_color: "#204270"

# Typography (can be customized to accomodate more styles like standard font sizes and line height)
fonts:
  fonts_code_block:  '<link href="/styles/fonts.css" rel="stylesheet">' # Place between single quotes
  body_font_family: "'ProximaNovaRegular', sans-serif;"
  body_alt_font_family: "'P22UndergroundRegular', sans-serif;"
  header_bold_font_family: "'ProximaNovaBlack', sans-serif;"
  header_font_family: "'ProximaNovaCond', sans-serif;"
  accent_font_family: "'AlternateGothicRegular', sans-serif;"

seo:
  fb_app_id: 123456789
  keywords: [chiang mai, startup, thailand visa, thailand freelancer visa, thailand work visa, work visa thailand]
  description: Draper Startup House connects you to Chiang Mai's startup ecosystem.

# Analytics & embeds
configuration:
  google_tag_manager_code_block:
  google_analytics_code_block:
  form_submission_handler_code_block:
  flexbox_framework_code_block: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">'
