# Basic settings
basics:
  site_title: My amazing website
  site_base_url: 'https://mysite.com'
  site_thumb_image: "assets/images/placeholder-001.jpg"
  contact_email: 'example@me.com'
  phone_number: "+555 555 5555"
  address: 1 Main Street, Springfield 90009
social:
  facebook_url: 'https://facebook.com'
  instagram_url: 'https://instagram.com'
  instagram_handle: '@yourhandle'
  twitter_url: 'https://twitter.com'
  twitter_handle: '@yourhandle'
  youtube_url: 'https://youtube.com'
  github_url: 'https://github.com'
  linkedin_url: 'https://linkedin.com'
  snapchat_url: 'https://snapchat.com'
  stackoverflow_url: 'https://stackoverflow.com'

# Brand identity
logos:
  navbar_logo_image: '/assets/logos/your-logo.png'
  footer_logo_image: '/assets/logos/your-logo-alternative.png'

# Global colors. Put HEX values between quotes otherwise it will act as a comment in YAML
colors:
  primary_color: "#000"
  secondary_color: "#555"
  primary_shade_color: "#222"
  secondary_shade_color: "#565"
  accent_color: "#999"

# Typography (can be customized to accomodate more styles like standard font sizes and line height)
fonts:
  fonts_code_block:  '<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Nunito&display=swap" rel="stylesheet">' # Place between single quotes
  body_font_family: "'Nunito', sans-serif;"
  design_font_family: "'Abril Fatface', cursive;"

seo:
  fb_app_id: 123456789
  keywords: [keyword, seo, optimization]
  description_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Analytics & embeds
configuration:
  google_analytics_code_block:
  form_submission_handler_code_block:
  flexbox_framework_code_block: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">'
  fontawesome_code_block:
